apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kkbz20867-go 
  janus-idp.io/tekton: kkbz20867-go
  backstage.io/kubernetes-id: kkbz20867-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kkbz20867-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml