apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kkbz20867-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kkbz20867-go 
  name: kkbz20867-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kkbz20867-go 
